version: 2.1
orbs:
  docker: circleci/docker@0.5.0
jobs:
#  shellcheck:
#    - docker:
#      image: koalaman/shellcheck-alpine:stable
#    - steps:
#      - checkout
#      - run:
#          name: Check Scripts
#          command: |
#            find . -type f -name '*.sh' | wc -l
#            find . -type f -name '*.sh' | xargs shellcheck --severity=error --external-sources
  check-and-build-only:
    working_directory: ~/repo/base-image
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout:
          path: ~/repo/images/base-image
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/apibuilder-demo-base

workflows:
  version: 2
  workflow:
    jobs:
#      - shellcheck
     - check-and-build-only:
        context: Dev-Tag-Service
