version: 2.1
orbs:
  docker: circleci/docker@0.5.0
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Check Scripts
          command: |
            find ~/repo -type f -name '*.sh' | wc -l
            find ~/repo -type f -name '*.sh' | xargs shellcheck --severity=error --external-sources
  check-and-build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/check
      - run:
          name: "Setup custom environment variables"
          command: |
            echo "FROM_VERSION=$CIRCLE_SHA1"
      - docker/publish:
          extra_build_args: '--squash'
          dockerfile: ~/repo/images/base-image/Dockerfile
          path: ~/repo/images/base-image
          registry: brianmlima
          image: apibuilder-demo-base
          tag: $CIRCLE_SHA1
      - docker/publish:
          extra_build_args: '--squash --build-arg FROM_VERSION=$CIRCLE_SHA1'
          dockerfile: ~/repo/images/apibuilder-image/Dockerfile
          path: ~/repo/images/apibuilder-image
          registry: brianmlima
          image: apibuilder-demo-app
          tag: $CIRCLE_SHA1

workflows:
  version: 2
  workflow:
    jobs:
     - shellcheck
     - check-and-build:
        context: Dev-Tag-Service
