version: 2.1
orbs:
  docker: circleci/docker@0.5.0
jobs:
#  shellcheck:
#    - docker:
#      image: koalaman/shellcheck-alpine:stable
#    - steps:
#      - checkout
#      - run:
#          name: Check Scripts
#          command: |
#            find . -type f -name '*.sh' | wc -l
#            find . -type f -name '*.sh' | xargs shellcheck --severity=error --external-sources
  check-and-build-only:
#    working_directory:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/check
      - docker/build:
          dockerfile: ~/repo/images/base-image/Dockerfile
          path: ~/repo/images/base-image
          label_prefix: brianmlima
          image: apibuilder-demo-base
          tag: $CIRCLE_SHA1
      - docker/build:
          extra_build_args: '--build-arg FROM_VERSION=$CIRCLE_SHA1'
          dockerfile: ~/repo/images/apibuilder-image/Dockerfile
          path: ~/repo/images/apibuilder-image
          label_prefix: brianmlima
          image: apibuilder-demo-app
          tag: $CIRCLE_SHA1

workflows:
  version: 2
  workflow:
    jobs:
#      - shellcheck
     - check-and-build-only:
        context: Dev-Tag-Service
