version: 2.1
orbs:
  docker: circleci/docker@0.5.0

jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --severity=error --external-sources
  check-and-build-only:
    docker:
    - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
#      - docker/check
      - docker/build:
          path: images/base-image
          image: $CIRCLE_PROJECT_USERNAME/apibuilder-demo-base



#  build-job:
#    docker:
#      - image: koalaman/shellcheck-alpine:stable
#    steps:
#    - checkout
#    - docker/install-docker-tools
#    - run:
#      name: Build Images
#      command: |
#        ./bin/build.sh
workflows:
  version: 2.1
  workflow:
    jobs:
      - shellcheck
      - check-and-build-only
#        requires:
#          - shellcheck
#      - docker/build:
#          dockerfile: Dockerfile
#          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
#          path: images/base-image
#          registry: my.docker.registry


#      - build-job:
#          requires:
#            - shellcheck
#          filters:
#            branches:
#              only: master
